Recursive principles for the Cumulative hierarchy
UniMath/agda-unimath pull request #493
Opened 2023-03-08 18:05 UTC by shiranaiyo

I've followed very closely [Tom's work](https://www.cs.bham.ac.uk/~mhe/agda/UF.CumulativeHierarchy.html) as those recursion principles are very useful. However I've also noticed that no recursion principles have been stated in agda-unimath (at least not with that name), so I'm unsure if this is the correct naming scheme.

I left the last one in a comment as I wanted to check the name too. It also made me realize I needed `is-set (Prop l)`. Which can be seen as a particular case of
![image](https://user-images.githubusercontent.com/17756312/223793809-411e194e-b76b-4cb9-8f9a-6912e3735b57.png)

Just double checking, this isn't in the library yet, right?

2023-03-08 18:16 UTC, fredrik-bakke commented
Hi Fernando! I'll quickly answer your questions.

> I've followed very closely [Tom's work](https://www.cs.bham.ac.uk/~mhe/agda/UF.CumulativeHierarchy.html) as those recursion principles are very useful. However I've also noticed that no recursion principles have been stated in agda-unimath (at least not with that name), so I'm unsure if this is the correct naming scheme.

I'm unsure why this is the case other than that recursion principles are just special cases of induction principles. My feeling is it would not be wrong to add a recursion principle kind of statement to the library. Indeed, in one of my newest PRs I am also doing this.

> I left the last one in a comment as I wanted to check the name too. It also made me realize I needed `is-set (Prop l)`. Which can be seen as a particular case of ![image](https://user-images.githubusercontent.com/17756312/223793809-411e194e-b76b-4cb9-8f9a-6912e3735b57.png)
> 
> Just double checking, this isn't in the library yet, right?

This is formalized  as `is-set-Prop` on lines 88-90 in `foundation.sets`.

2023-03-08 18:34 UTC, fredrik-bakke requested changes

2023-03-08 18:34 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +  --   recursion-principle-cumulative-hierarchy-V (Prop l2) {!!} ρ {!!}
commented code should be removed

2023-03-08 18:34 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +      → type-pseudo-cumulative-hierarchy V → X
This is a very minor point, but our convention is to place arrows at the end of lines instead of the beginning in cases like this.
Cf. <https://unimath.github.io/agda-unimath/CODINGSTYLE.html> (under Indentation)

2023-03-08 18:34 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +  recursion-principle-cumulative-hierarchy-V : {l2 : Level}
The name of this construction should not reference variable names (i.e. here `V`). I suggest `recursion-principle-cumulative-hierarchy` instead.
Cf. <https://unimath.github.io/agda-unimath/CODINGSTYLE.html> (under Names)

2023-03-08 18:34 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +  compute-recursion-principle-cumulative-hierarchy-V : {l2 : Level}
this name also references a variable

2023-03-08 18:50 UTC, shiranaiyo commented
@fredrik-bakke thank you! I'll be implementing the suggestions soon. With respect to `is-set (Prop l)`, I think it is very different from `is-set-Prop` in `foundation.sets`. The latter just being that for any `A` we have a Prop, that of `is-set A`. So it's kind of the other way around.

2023-03-08 18:52 UTC, fredrik-bakke commented
Oh, yeah, you're absolutely right! I didn't even bother reading what `is-set-Prop` actually did before I responded. My bad!

2023-03-08 19:09 UTC, fredrik-bakke commented
I am also unable to find Theorem 7.1.11 formalized in the library.
I can note that
- Theorem 7.1.6 is `is-trunc-emb`
- the statement `(A ≃ B) ↪ (A → B)` is `emb-map-equiv`
- And Lemma 3.5.1 should be easy to prove if it's not already in the library

2023-03-08 19:16 UTC, shiranaiyo commented
Haha np, funny how `is-set-Prop` can be interpreted both ways. I think I've found 7.1.11 as `is-trunc-Truncated-Type` in `foundations.truncated-types`, but since `Prop` is not judgementally equal to the type of propositional truncations the lemma `is-set (Prop l)` is still needed. I'd appreciate name suggestions for it.

2023-03-08 19:21 UTC, fredrik-bakke commented
Would you look at that.

Also, I'm unsure what you mean. The following type checks for me

```agda
is-set-Prop' : (l : Level) → is-set (Prop l)
is-set-Prop' l = is-trunc-Truncated-Type (neg-one-𝕋)
```

2023-03-08 19:25 UTC, shiranaiyo commented
Yeah I found `is-trunc-Truncated-Type` because I was about to implemented it but agda complained it already existed. Yay for consistent naming schemes :)

Forgot `Prop` here is defined differently than in the HoTT book, thanks! I'll continue with the cumulative hierarchy then, just using `is-trunc-Truncated-Type (neg-one-𝕋)` when needed.

2023-03-08 19:26 UTC, fredrik-bakke commented
Sounds like a good solution for now. I am a little annoyed with `is-set-Prop` at the moment.

2023-03-08 21:00 UTC, EgbertRijke commented
The file `foundation.propositional-extensionality` contains the statement you want. It is called `is-set-type-Prop`

2023-03-08 21:06 UTC, EgbertRijke commented
I think the confusing naming comes from when we converted to `--no-import-sorts`. This allowed us to rename `UU-Prop` to `Prop`. The names were previously `is-set-Prop` for the property that something is a set and `is-set-UU-Prop` for the theorem that `UU-Prop` is a set. After converting from `UU-Prop` to `Prop` this name clash came to the surface, and apparently I went with the subobtimal `is-set-type-Prop`. I'm open to other suggestions.

2023-03-08 21:26 UTC, EgbertRijke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +        ( λ f → set-pseudo-cumulative-hierarchy V f ＝ v))
If you want to follow our line-breaks conventions here, this should be:

```
    ∃ ( UU l1)
       ( λ A → 
         Σ ( A → type-pseudo-cumulative-hierarchy V)
           ( λ f → set-pseudo-cumulative-hierarchy V f ＝ v))
```

If a lambda-expression doesn't fit on a line, make a line break immediately after the arrow.

2023-03-08 21:27 UTC, EgbertRijke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +      ( λ - → is-trunc-type-Truncated-Type (set-trunc-Prop _))
The dash symbol of this lambda should be `_`, not `-`

2023-03-09 06:42 UTC, shiranaiyo commented on src/set-theory/cumulative-hierarchy.lagda.md
> +        ( λ f → set-pseudo-cumulative-hierarchy V f ＝ v))
Thanks, I didn't understand well the style guide but I think I do now. I've modified it now.

2023-03-09 06:42 UTC, shiranaiyo commented on src/set-theory/cumulative-hierarchy.lagda.md
> +      ( λ - → is-trunc-type-Truncated-Type (set-trunc-Prop _))
Corrected.

2023-03-09 06:43 UTC, shiranaiyo commented
This last commit adds some other useful principles, corrects that the `lift` properties should be propositionally truncated, and implements the membership relation (finally!).

2023-03-09 08:32 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +                       (λ p → tr P p (IH₂ b) ＝ IH₁ a))) →
indentation

2023-03-09 08:33 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +```
``````
```agda
``````

2023-03-09 08:43 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +        ( λ _ → IH₂ b ＝ IH₁ a))) →
indentation/product

2023-03-09 08:44 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +      ( (a : A) → ∃ B (λ b → Σ (f a ＝ g b)
indentation/product

2023-03-09 08:47 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +        ( ∃ A (λ a → f a ＝ x) → ∃ B (λ b → g b ＝ x))
Add a line break to keep things aligned
```agda
e :
  {A B UU l1} ...
```
Cf. <https://unimath.github.io/agda-unimath/CODINGSTYLE.html> (under Indentation)

2023-03-09 08:49 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +      τ' : {A B : UU l1} (f : A → pr1 V) (g : B → pr1 V)
line break after `τ' :`

2023-03-09 08:49 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +    ( τ : {A B : UU l1} (f : A → type-pseudo-cumulative-hierarchy V)
line break after `τ :`

2023-03-09 16:40 UTC, shiranaiyo commented
Thank you @fredrik-bakke, I apologize for not following the guidelines earlier. I believe I'm following all of them now.

2023-03-09 17:37 UTC, fredrik-bakke commented
You mustn't apologize, that's why we review! 🙂

To fix CI, install pre-commit (see how-to-install) and then run `make pre-commit` in the terminal

2023-03-09 18:17 UTC, shiranaiyo commented
Yup, I got it passing now, thanks.

2023-03-09 22:20 UTC, fredrik-bakke commented on src/set-theory/cumulative-hierarchy.lagda.md
> +    ( τ : {A B : UU l1} (f : A → type-pseudo-cumulative-hierarchy V)
Missed a spot 😬

2023-03-09 22:23 UTC, fredrik-bakke commented
This is certainly good enough to merge now. Excellent work! 😁

2023-03-09 22:24 UTC, merged