Eckmann-Hilton in the Universe
UniMath/agda-unimath pull request #703
Opened 2023-08-21 20:53 UTC by morphismz

This pr formalizes most of the "Eckmann-Hilton in the universe" idea.

The main theorem of the pr, named `tr³-htpy-swap-path-swap`, establishes that `tr³` sends `path-swap` to `htpy-swap`.

2023-08-21 20:55 UTC, morphismz commented
I'm having trouble with the pre-commit tool. Its throwing an error, but I can't tell whats causing it.

2023-08-21 21:01 UTC, EgbertRijke commented on src/foundation/transport.lagda.md
> +          ( path-swap-nat-identification-left-whisk β α) b0)
It looks like `b0` at the end is an argument of `tr³`. It should therefore receive a line break and be indented at the same level as the other two arguments of `tr³`.

The argument `( tr-concat p' q' b0)` however is not an argument of `tr³` so it is not logical to display it at the same indentation level as the arguments of `tr³`. It should receive two spaces less indentation, so that it is clear that it is an argument of `identification-right-whisk`

2023-08-21 21:05 UTC, EgbertRijke commented
> I'm having trouble with the pre-commit tool. Its throwing an error, but I can't tell whats causing it.

Can you show us the output of `make pre-commit`?

2023-08-21 21:12 UTC, morphismz commented
> > I'm having trouble with the pre-commit tool. Its throwing an error, but I can't tell whats causing it.
> 
> Can you show us the output of `make pre-commit`?

Here is the out put: 
![Screenshot from 2023-08-21 15-10-22](https://github.com/UniMath/agda-unimath/assets/96847663/128ac06b-aac5-4a8c-a4b2-365c89a75bd4)

2023-08-21 21:13 UTC, morphismz commented on src/foundation/transport.lagda.md
> +          ( path-swap-nat-identification-left-whisk β α) b0)
oh, wow, thanks so much!

2023-08-21 21:19 UTC, morphismz commented
I might also be formatting concatenation of paths wrong, let me work on that

2023-08-21 21:29 UTC, EgbertRijke commented
Ah, it is not telling us which files were modified. @fredrik-bakke, do you think it would be better if it told us which files were modified?

One trick to see which files are being modified is to commit all your changes, then run `make pre-commit` and see from the git logs which files are being modified/problematic.

2023-08-21 21:56 UTC, VojtechStep commented
I think the offender is printed at the end of the log, and it's the `transport` file. I see that one of the code blocks is missing the language declaration (i.e. it starts with just triple backticks, without `agda`), which probably breaks Fredrik's parser, I remember it being sensitive to that stuff.

2023-08-21 22:04 UTC, morphismz commented
> I think the offender is printed at the end of the log, and it's the `transport` file. I see that one of the code blocks is missing the language declaration (i.e. it starts with just triple backticks, without `agda`), which probably breaks Fredrik's parser, I remember it being sensitive to that stuff.

great catch, I'll fix that and see what happens. Maybe there is way for the parser to report back that a code block is set up right?

2023-08-22 07:44 UTC, fredrik-bakke commented
> Ah, it is not telling us which files were modified. @fredrik-bakke, do you think it would be better if it told us which files were modified?
> 
> One trick to see which files are being modified is to commit all your changes, then run `make pre-commit` and see from the git logs which files are being modified/problematic.

I totally agree that it should display which files are modified, but as far as I can recall, there didn't seem to be a way to make `pre-commit` do that. If any of you know of a way, that would be greatly appreciated!

2023-08-22 07:45 UTC, fredrik-bakke commented
> I think the offender is printed at the end of the log, and it's the `transport` file. I see that one of the code blocks is missing the language declaration (i.e. it starts with just triple backticks, without `agda`), which probably breaks Fredrik's parser, I remember it being sensitive to that stuff.

The parser doesn't break, it deliberately looks for ill-formed blocks and reports them. However, `pre-commit` makes it seem like scripts break when they simply report an error at times.

2023-08-22 07:46 UTC, fredrik-bakke commented
Or, at least, it _shouldn't_ break. If you find that it does that, please report it!

2023-08-22 07:56 UTC, VojtechStep commented
In May you wrote
> So one of my `pre-commit` scripts doesn't accept unspecified code blocks. So far, that has only ever been due to typos. But if `text` works, that would be great
on the Discord, which I interpreted as "it breaks on unspecified code blocks", but if it intentionally rejects them, then that's great 👌

2023-08-22 07:57 UTC, fredrik-bakke commented
> In May you wrote
> 
> > So one of my `pre-commit` scripts doesn't accept unspecified code blocks. So far, that has only ever been due to typos. But if `text` works, that would be great
> 
> on the Discord, which I interpreted as "it breaks on unspecified code blocks", but if it intentionally rejects them, then that's great 👌

Aha, I guess I should've said "rejects". Sorry about that!

2023-08-22 08:01 UTC, VojtechStep commented
Wait, but then "Markdown conventions", which checks for well-formatted code blocks, should have triggered, right? Which it didn't?

2023-08-22 08:03 UTC, fredrik-bakke commented
Ah, that confused me too. I'll look into that!

2023-08-22 08:13 UTC, fredrik-bakke requested changes
It's unclear to me where we draw the line between what's foundational and what's synthetic homotopy theory. I think you could make an argument for placing the Eckmann-Hilton argument in either, but I'd assume users of the library would look in `synthetic-homotopy-theory` first. Do you have any opinion on this, @EgbertRijke? Also, do we want Eckmann-Hilton in its own file?

2023-08-22 08:13 UTC, fredrik-bakke commented on src/foundation/transport.lagda.md
> +#### Coherences and algebraic identities for tr³
```suggestion
#### Coherences and algebraic identities for `tr³`
```

2023-08-22 08:13 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +#### The above operations allow "swapping paths"
```suggestion
#### The whiskering operations allow us to commute higher identifications
```

2023-08-22 08:22 UTC, fredrik-bakke commented
By the way, you can link to your issue using its issue number, i.e. #702. GitHub will then place links in the appropriate places so that things get nicely catalogued. :) Also, if you write "closes #XYZ" or "resolves #XYZ", the appropriate issue will be closed when that PR is merged.

2023-08-22 15:52 UTC, morphismz commented on src/foundation/path-algebra.lagda.md
> +  identification-left-whisk p β = horizontal-concat-Id² (refl {x = p}) β
I'll have to think about this a bit more. Though, of course, they will be prepositionally equal, the syntactic behavior of these things will be sufficiently different. Your change probably will be just fine, but I'll mull it over

2023-08-22 15:53 UTC, morphismz commented
> It's unclear to me where we draw the line between what's foundational and what's synthetic homotopy theory. I think you could make an argument for placing the Eckmann-Hilton argument in either, but I'd assume users of the library would look in `synthetic-homotopy-theory` first. Do you have any opinion on this, @EgbertRijke? Also, do we want Eckmann-Hilton in its own file?

I'm all for Eckmann-Hilton getting its own file! I just put this stuff in path algebra, since it seems vaguely related and there was no file with a more direct relation.

2023-08-22 15:54 UTC, morphismz commented on src/foundation/homotopies.lagda.md
> +    nat-htpy H12 (H01 x0)
oops, sorry, forgot about that...

2023-08-22 16:39 UTC, morphismz commented on src/foundation/path-algebra.lagda.md
> +  identification-left-whisk p β = horizontal-concat-Id² (refl {x = p}) β
You're so totally right. These are better

2023-08-22 20:44 UTC, fredrik-bakke approved these changes

2023-08-22 20:49 UTC, fredrik-bakke commented on src/foundation/transport.lagda.md
> +        ( htpy-swap-nat-right-htpy (tr² B β) (tr² B α) b))
```suggestion
    coherence-square-identifications
      ( identification-right-whisk
        ( tr³
          ( B)
          ( path-swap-nat-identification-left-whisk β α)
          ( b))
        ( tr-concat p' q' b))
      ( ( identification-right-whisk
          ( tr²-concat
            ( identification-right-whisk α q)
            ( identification-left-whisk p' β) b)
          ( tr-concat p' q' b)) ∙
      ( vertical-concat-square
        ( tr² B (identification-right-whisk α q) b)
        ( tr² B (identification-left-whisk p' β) b)
        ( tr-concat p' q' b)
        ( tr-concat p' q b)
        ( tr-concat p q b)
        ( htpy-left-whisk (tr B q) (tr² B α) b)
        ( htpy-right-whisk (tr² B β) (tr B p') b)
        ( tr²-right-whisk α q b)
        ( tr²-left-whisk p' β b)))
      ( ( identification-right-whisk
          ( tr²-concat (identification-left-whisk p β)
          ( identification-right-whisk α q') b)
          ( tr-concat p' q' b)) ∙
      ( vertical-concat-square
        ( tr² B (identification-left-whisk p β) b)
        ( tr² B (identification-right-whisk α q') b)
        ( tr-concat p' q' b)
        ( tr-concat p q' b)
        ( tr-concat p q b)
        ( htpy-right-whisk (tr² B β) (tr B p) b)
        ( htpy-left-whisk (tr B q') (tr² B α) b)
        ( tr²-left-whisk p β b)
        ( tr²-right-whisk α q' b)))
      ( identification-left-whisk
        ( tr-concat p q b)
        ( htpy-swap-nat-right-htpy (tr² B β) (tr² B α) b))
```

I don't suppose you know of a more readable type signature for this construction?

2023-08-22 20:51 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +    ( nat-htpy (htpy-identification-left-whisk β) α)
It seems you can write this as
```suggestion
  path-swap-nat-identification-left-whisk β =
    nat-htpy (htpy-identification-left-whisk β)
```

2023-08-22 20:54 UTC, fredrik-bakke commented
Things seem to be mostly in order now, but I made a couple of additional suggestions. Also, let's wait for Egbert's input before merging. Or do you want this merged as soon as possible?

2023-08-22 21:14 UTC, morphismz commented
> Things seem to be mostly in order now, but I made a couple of additional suggestions. Also, let's wait for Egbert's input before merging. Or do you want this merged as soon as possible?

No rush on my end, happy to get more feedback first!

2023-08-23 12:07 UTC, EgbertRijke commented on src/foundation/homotopies.lagda.md
> +  { f = f}
Can't we simply avoid introducing all these implicit arguments? You're not using them in the definition.

2023-08-23 17:23 UTC, morphismz commented on src/foundation/homotopies.lagda.md
> +  { f = f}
oops, you're right. I forget why I wrote those out...

2023-08-28 11:28 UTC, fredrik-bakke commented
Alright, I think we've waited long enough. If we want to move Eckmann-Hilton, we can do so at a later point. I will merge this PR when the checks pass. Thanks again for these contributions, I'm excited for all the new additions to `synthetic-homotopy-theory`! :)

2023-08-28 11:37 UTC, merged