Some computations for different notions of equivalence
UniMath/agda-unimath pull request #711
Opened 2023-08-27 17:47 UTC by fredrik-bakke

A collection of miscellaneous computations for logical equivalences, invertible maps, and involutions.
Invertible maps have been moved to their own module, separating them from coherently invertible maps.

2023-09-05 20:30 UTC, EgbertRijke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
This code block has no section title.

Also, it feels like the things in the following code block don't really belong in this file, because they are about propositions, sets, and truncated types.

2023-09-05 20:33 UTC, EgbertRijke commented on src/foundation-core/invertible-maps.lagda.md
> +### The type of inverse proofs
I would say: ``### The predicate that a map `g` is an inverse of a map `f` ``

The phrase "The type of inverse proofs" looks so clumsy

2023-09-05 20:34 UTC, EgbertRijke commented on src/foundation-core/invertible-maps.lagda.md
> +### The type of inverse proofs
```suggestion
### The predicate that a map `g` is an inverse of a map `f`
```

2023-09-05 20:35 UTC, EgbertRijke commented on src/foundation-core/invertible-maps.lagda.md
> +### The type of inverses of a map
```suggestion
### The predicate that a map `f` is invertible
```

2023-09-05 20:37 UTC, EgbertRijke commented on src/foundation-core/invertible-maps.lagda.md
> +### The inverse invertible map
```suggestion
### The invertible inverse of an invertible map
```

2023-09-05 20:43 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +#### Equivalence composition is associative
```suggestion
#### Composition of equivalences is associative
```

2023-09-05 20:44 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +#### Unit laws for equivalence composition
```suggestion
#### Unit laws for composition of equivalences
```

2023-09-05 20:45 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +#### Inverse laws for equivalence composition
```suggestion
#### Inverse laws for composition of equivalences
```

2023-09-05 20:47 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +#### Higher coherence between the unit laws for equivalence composition
```suggestion
#### A coherence law for the unit laws for composition of equivalences
```

2023-09-05 21:09 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +left-left-inverse-law-equiv f e =
I don't really understand the rationale behind this name change. The previous name was clearer in my opinion, and I don't think `left-left-inverse-law-equiv` is part of any existing naming scheme.

How about `is-retraction-postcomp-inv-equiv`? This fits in a naming scheme with `is-section-postcomp-inv-equiv`, `is-retraction-precomp-inv-equiv` and `is-section-precomp-inv-equiv`.

2023-09-05 21:18 UTC, fredrik-bakke commented on src/foundation/equivalences.lagda.md
> +left-left-inverse-law-equiv f e =
Sure, that sounds like a more reasonable naming scheme. Sorry, this was the first scheme I could think of. I introduced similar lemmas for identification concatenation as well, but I guess preconcat and postconcat make sense too

2023-09-05 21:21 UTC, fredrik-bakke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
I agree. They didn't really fit in `equivalences` either, where I moved them from. Perhaps some file about subuniverses would be better for these theorems

2023-09-05 21:43 UTC, fredrik-bakke commented
Thank you for the comments! I will try and address them tomorrow

2023-09-05 21:49 UTC, EgbertRijke requested changes
There is a lot of good work in this PR. I reviewed 100 files so far, but it is taking my quite long so I leave it here for now.

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +is-equiv-left-comp-equiv :
I don't think we should speak of "left composition" and "right composition". The usual terminology is "postcomposition" and "precomposition"

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +### Left and right composition by an equivalence defines equivalences
```suggestion
### The Postcomposition and precomposition operations by an equivalance are equivalences
```

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +pr2 (equiv-postcomp-equiv f A) = is-equiv-left-comp-equiv f A
Here it shows that the name is clearly off

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +  map-map-over-equiv-over : equiv-over f g i → map-over f g i
In the previous name I liked that by the prefix `map-emb` it clearly showed the intention that it was the underlying map of an embedding. If we're going to shorten this name, I think I like `map-over-equiv-over` better. We never use `map-abc-xyz` as a naming scheme for maps from `xyz` to `abc`. We'd simply use the name `abc-xyz` for such cases.

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
>    map-fibered-map-fibered-equiv : fibered-equiv f g → fibered-map f g
In line with my previous comment, this should probably be called `fibered-map-fibered-equiv`

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/functoriality-function-types.lagda.md
> +### A map is truncated iff postcomposition by it is truncated
This feels more like something that belongs in the file about truncated maps

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
Actually, there should be `coherence-htpy-is-section` and `coherence-htpy-is-retraction` in the files about sections and retractions, and this definition should be reusing those characterizations of equality.

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/invertible-maps.lagda.md
> +        (is-contr-total-Eq-structure
```suggestion
        ( is-contr-total-Eq-structure
```

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +### the unit laws of concatenation induced homotopies
```suggestion
### The unit laws of concatenation induce homotopies
```

Present tense conveys the meaning better.

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  left-left-inv :
```suggestion
  is-retraction-left-concat-inv :
```

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  left-right-inv :
```suggestion
  is-section-left-concat-inv :
```

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  right-left-inv :
```suggestion
  is-section-right-concat-inv :
```

2023-09-05 21:49 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  right-right-inv :
```suggestion
  is-retraction-right-concat-inv :
```

2023-09-05 22:05 UTC, fredrik-bakke commented
Thank you so much! I'm really sorry for making you review so many files. In the other PR, I can revert the naming change of `foundation.transport` to make the size more manageable

2023-09-06 08:37 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  left-left-inv :
I'm also fine with `preconcat` and `postconcat` although we don't use those words yet in the library.

2023-09-06 10:45 UTC, fredrik-bakke commented on src/foundation-core/invertible-maps.lagda.md
> +### The type of inverse proofs
I wanted to avoid "predicate", but I guess it won't really cause confusion

2023-09-06 14:50 UTC, EgbertRijke commented on src/foundation/equivalences.lagda.md
> +left-left-inverse-law-equiv f e =
Good suggestion! I like this even more than my original suggestion.

2023-09-06 14:51 UTC, fredrik-bakke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
So, homotopies of retractions are defined in terms of homotopies in the coslice. Do you prefer if homotopies of sections are similarly characterized in terms of homotopies in the slice, or do you want an independent definition of homotopies of retractions?

Personally, I find retractions to be a more central notion than homomorphisms in the coslice, so perhaps we can swap directions and define homotopies in the coslice in terms of homotopies of retractions?

2023-09-06 14:56 UTC, EgbertRijke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
I'm not sure what you have in mind. How would you define homotopies in the coslice as homotopies of retractions?

2023-09-06 14:56 UTC, fredrik-bakke commented on src/foundation/fibered-equivalences.lagda.md
> +  map-map-over-equiv-over : equiv-over f g i → map-over f g i
Since these maps can also be seen as projections, I think I prefer the name `map-over-equiv-over`.

2023-09-06 14:58 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +  map-map-over-equiv-over : equiv-over f g i → map-over f g i
Great! Then we agree that `map-over-equiv-over` is to be preferred over `map-map-over-equiv-over`

2023-09-06 14:58 UTC, fredrik-bakke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
```agda
module _
  {l1 l2 : Level} {A : UU l1} {B : UU l2} {f : A → B}
  where

  htpy-retraction : retraction f → retraction f → UU (l1 ⊔ l2)
  htpy-retraction = htpy-hom-coslice
```

2023-09-06 15:00 UTC, fredrik-bakke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
Ah, I guess the other way around doesn't really make sense. Sorry, I'm writing to you while attending a lecture

2023-09-06 15:01 UTC, EgbertRijke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
That's defining `htpy-retraction` in terms of `htpy-hom-coslice`. I understand this direction, but I thought you were suggesting the other direction, i.e., defining `htpy-hom-coslice` in terms of `htpy-retraction`.

2023-09-06 15:02 UTC, EgbertRijke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
Must be an interesting lecture:)

2023-09-06 15:03 UTC, fredrik-bakke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
My apologies, I am just wrong. So do you want `htpy-section` defined in terms of `htpy-hom-slice`, or to have independent definitions for both sections and retractions?

2023-09-06 15:04 UTC, fredrik-bakke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
I think it is, I'm just too stupid to follow it

2023-09-06 15:10 UTC, EgbertRijke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
I would not be very sure if that isn't going to create cyclic dependencies. In my above comment I was just suggesting to reuse the characterization of identity types of sections in the characterization of identity types of invertible maps. That would require factoring out `coherence-htpy-section` from the definition of `htpy-section`, but once that is done it can be reused in the definition of `coherence-htpy-is-invertible`. 

So I think I'm suggesting something simpler, but indeed it is also possible to do it in terms of `htpy-hom-coslice`. If that goes through I would be happy with that idea as well.

2023-09-06 15:12 UTC, fredrik-bakke commented on src/foundation/invertible-maps.lagda.md
> +    ( ( is-retraction-is-invertible s) ~
Okay, I will have to look into this another day

2023-09-07 09:05 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +  is-emb-map-over-equiv-over = is-emb-map-emb emb-map-over-equiv-over
It would be reasonable to also include `emb-map-over-equiv-over` below, for the embedding.

2023-09-07 09:05 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +  is-emb-fibered-map-fibered-equiv : is-emb fibered-map-fibered-equiv
You could also include `emb-fibered-map-fibered-equiv` below

2023-09-07 09:07 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +    ( e ＝ e')
```suggestion
    htpy-map-over f g i
      ( map-over-equiv-over f g i e)
      ( map-over-equiv-over f g i e') →
    e ＝ e'
```

2023-09-07 09:10 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +    ( ap (fibered-map-fibered-equiv f g) ,
This could be `equiv-ap-emb (emb-fibered-map-fibered-equiv f g)` instead of the explicit pair, if you would define `emb-fibered-map-fibered-equiv`. That would slightly simplify this proof term, because having an explicit pair looks odd here.

2023-09-07 09:11 UTC, EgbertRijke commented on src/foundation/fibered-equivalences.lagda.md
> +    ( e ＝ e')
```suggestion
    htpy-fibered-map f g
      ( fibered-map-fibered-equiv f g e)
      ( fibered-map-fibered-equiv f g e') →
    e ＝ e'
```

2023-09-07 09:17 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
It feels odd to have half a naming scheme `assoc-[left/middle/right]-refl` and half a naming scheme `unit-law-assoc-xxx`. At least it was more consistent previously.

2023-09-07 09:30 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
The specification of this operation looks a little strange to me, and I'm not convinced it is in its most useful form. Could you explain why you gave it this specification?

2023-09-07 09:32 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/extensions-of-maps.lagda.md
> +  equiv-is-contr-extension-Π-is-local-Π :
What was wrong with the terminology `is-local-family`?

2023-09-07 09:33 UTC, fredrik-bakke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
The idea here was to mimic `equiv-Pi` if I recall correctly

2023-09-07 09:36 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/local-types.lagda.md
> +  is-local-Π : {l : Level} → (X → UU l) → UU (l1 ⊔ l2 ⊔ l)
Given how we name things in agda-unimath, `is-local-Π` reads like the property that a dependent function type is local. That is not what is asserted here, so the name `is-local-Π` doesn't look right to me.

2023-09-07 09:39 UTC, fredrik-bakke commented on src/orthogonal-factorization-systems/local-types.lagda.md
> +  is-local-Π : {l : Level} → (X → UU l) → UU (l1 ⊔ l2 ⊔ l)
I agree, I just didn't come up with a better name. Originally it was called `is-local'` I believe. Maybe the best name would be `is-local-dependent-type`. (Then we should make a similar renaming for extension types)

2023-09-07 09:40 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/pullback-hom.lagda.md
> +      ( is-pullback-fibered-map f' g')
```suggestion
    map-is-pullback
      ( precomp f Y)
      ( postcomp A g)
      ( precomp f' Y')
      ( postcomp A' g')
      ( cone-pullback-hom f g)
      ( cone-pullback-hom f' g')
      ( is-pullback-fibered-map f g)
      ( is-pullback-fibered-map f' g')
```

2023-09-07 09:40 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/pullback-hom.lagda.md
> +      ( precomp f Y) (postcomp A g) →
```suggestion
    hom-cospan
      ( precomp f' Y')
      ( postcomp A' g')
      ( precomp f Y)
      ( postcomp A g) →
```

2023-09-07 09:46 UTC, fredrik-bakke commented on src/foundation/fibered-equivalences.lagda.md
> +    ( ap (fibered-map-fibered-equiv f g) ,
That's nice. Thanks for the tip!

2023-09-07 09:48 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
I agree, I just didn't want to touch the old stuff. To be honest I want to remove it

2023-09-07 10:08 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
We should start the habit of opening issues for this:)

2023-09-07 10:10 UTC, EgbertRijke commented
I reviewed all the files now. If we address all the issues, this PR will be ready to be merged. Thanks for doing all this work!

2023-09-07 10:20 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Such laws are actually coming up in A2-spaces. I don't think they should be removed.

2023-09-07 10:25 UTC, fredrik-bakke commented
Great! I'll address the remaining ones as soon as I have time. Thanks again for taking the time

2023-09-07 10:25 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
The problem is that with logical equivalences, there are a lot more nonequivalent ways to construct equivalences between Pi-types. I don't think it is clear that this is the preferred/canonical choice. With equivalences, things are a bit more restrictive because you have a 1-1 correspondence between elements of the domain and codomain.

I also wonder if this form of `iff-Π` is actually used somewhere. I don't recall seeing it showing up in this PR, but I might just have missed it. If there are no uses for `iff-Π` then I might have a preference to rename `iff-Π-iff-fam` back to `iff-Π` because that one actually sees some use.

2023-09-07 10:26 UTC, fredrik-bakke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
That's actually not a terribly bad idea! We'll generate a lot of good first issues this way, and it might also give a hint as to what people are working on/interested in

2023-09-07 10:29 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
I always thought that "good first issue" means that it is a good issue and it is the first issue from a new contributor. But now you seem to say that it is more like a good first task to work on for a new contributor. Perhaps we should have a clearer label than "good first issue" because to be honest I thought about removing that label altogether because I thought it was so useless:)

2023-09-07 10:31 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
Is there also a way to link back to issues in agda-unimath website? Then we could mention that in those "remains to be formalized" remarks.

2023-09-07 10:39 UTC, fredrik-bakke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
> I always thought that "good first issue" means that it is a good issue and it is the first issue from a new contributor. But now you seem to say that it is more like a good first task to work on for a new contributor. Perhaps we should have a clearer label than "good first issue" because to be honest I thought about removing that label altogether because I thought it was so useless:)

Oh, haha, the latter is the generally accepted meaning I think. 😅 I've been a bit sloppy with how I use it, so sorry if that's caused further confusion. What do you propose instead? Something like `newcomer friendly`? For what it's worth,  I do believe `good first issue` is pretty widely used.

2023-09-07 10:41 UTC, fredrik-bakke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
Appending `[#xyz](link)` should suffice

2023-09-07 11:19 UTC, fredrik-bakke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
So, just to make sure. The definition `iff-Π-iff-fam` imitates `equiv-Π-equiv-fam`. Do you want to break this pattern as well? I understand that logical equivalences and equivalences are very different notions, but still, given its name and usage, I was under the impression that it should imitate equivalences. The principle I was following when making these changes was that every construction in logical equivalences with a corresponding construction in equivalences is mapped to it under `iff-equiv`.

2023-09-08 10:36 UTC, fredrik-bakke commented on src/foundation/fibered-equivalences.lagda.md
> +  is-emb-map-over-equiv-over = is-emb-map-emb emb-map-over-equiv-over
This is defined 10 lines further up.

2023-09-08 10:36 UTC, fredrik-bakke commented on src/foundation/fibered-equivalences.lagda.md
> +  is-emb-fibered-map-fibered-equiv : is-emb fibered-map-fibered-equiv
This is defined 9 lines further up.

2023-09-08 11:01 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Alright, how do you feel about the current names? I don't like that `transpose-assoc-middle-refl` introduces a new naming scheme, but I didn't find the alternative `assoc-middle-refl'` to be much better.

2023-09-08 11:07 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Also, I just realized that the `con` in `inv-con` stands for concatenation. However, we don't use the abbreviation `con` for concatenation anywhere else (`(?<!inv-)\bcon\b(?!-inv)`). Perhaps we can give `inv-con` and `con-inv` new names? Something like `left-transpose` and `right-transpose`

2023-09-08 12:33 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
I agree, but please in another PR that is just for that purpose.

2023-09-08 12:35 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
I still like to call them unit laws for associators, and I don't see why it is a good idea to give that up. It aligns well with unit laws for binary operations, and to me there is no reason why multivariable operators such as associators shouldn't have unit laws. But I like your [left/middle/right], so my preferred naming would be `[left/middle/right]-unit-law-assoc`.

2023-09-08 12:38 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
But actually the point with the binary number notation had a purpose. Actually there are 7 unit laws for the associator: Three of them have refl in one of the arguments, 3 of them have refl in two of the arguments, and one of them is a coherence that puts them all together and it has refl in all three of the arguments. The old naming scheme was supposed to make naming the other 4 unit laws (or coherences) easy to name.

2023-09-08 12:40 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
With the pentagonator there will be 15 unit laws. More generally, n-ary operations may have 2^n -1 unit laws.

2023-09-08 13:53 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
The binary numbering scheme makes sense to me. However, currently, there are 6 unit laws recorded for the associator where only one of the arguments is reflexivity, not just 3. The general naming scheme seems to have been to just append primes for different variants of the same unit law. It makes sense that there are more unit laws for some of the positions since concatenation computes on the left and not on the right, but I don't see the pattern for which variant has fewer primes than the other. In particular, I have a problem with what was defined as "the" right unit law. What previously had the name `unit-law-assoc-110` I expected to have type `assoc p q refl ＝ ...`. However, instead, it was an equality of type `(assoc p q refl ∙ ap (concat p z) right-unit) ＝ ...`, and the unit law that I was looking for was not recorded at all.

2023-09-08 13:59 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
That's perhaps because I transposed them in order to state them free of inverses.

2023-09-08 14:00 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Probably the reason I did that was because then it will be easier to state the coherences between them (with refl twice or three times in the arguments of assoc)

2023-09-08 14:03 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
When it would have been stated using `coherence-triangle-identifications` it would have been clearer, because `assoc p q refl` would just be one of the sides of the triangle.

2023-09-08 14:07 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Ah, okay, that makes sense. So then maybe it _is_ a good idea to use two different naming schemes. One for the collection of unit laws and their coherences, and one for computing with the associator.

2023-09-08 14:08 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Lol, but then we would both win

2023-09-08 14:10 UTC, EgbertRijke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Anyway, that sounds good. Perhaps keep then near each other and add a short explanation of what is going on.

2023-09-08 14:10 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Oh, shoot, we can't have that

2023-09-08 14:10 UTC, fredrik-bakke commented on src/foundation/path-algebra.lagda.md
> +  unit-law-assoc-101' :
Yep, sounds good!

2023-09-08 14:20 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
Is `equiv-Π-equiv-fam` the same as `equiv-map-Π`?

2023-09-10 12:23 UTC, fredrik-bakke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
Ohh, whoops, I see I reverted that change. Sorry for the confusion. Then perhaps `iff-Π-iff-fam` should be named `iff-map-Π`?

2023-09-10 12:38 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
How about `equiv-Π-family-of-equivalences` and `iff-Π-family-of-logical-equivalences`? We also spell out "family of elements" elsewhere in the library, and I think it reads better than `equiv-fam`. The old name `equiv-map-Π` also doesn't seem quite right to me.

2023-09-10 12:53 UTC, fredrik-bakke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
I think I prefer `equiv-Π-equiv-family`. I don't like how your suggestions seem to use two different names for the same notions. E.g. `equiv` and `equivalence`, and `iff` and `logical-equivalence`. Moreover, the `-of-` binding in definition names doesn't seem to fit too well with our general naming scheme.

2023-09-10 12:57 UTC, fredrik-bakke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
If it is okay with you, I will create issues for empty sections like this in a separate PR.

2023-09-10 13:01 UTC, EgbertRijke commented on src/orthogonal-factorization-systems/local-maps.lagda.md
> +This remains to be formalized.
Sure!

2023-09-10 13:03 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
We should probably define `equiv-family` somewhere, so that `equiv-Π-equiv-family` reads as the function that takes an element of type `equiv-family` to an equivalence of dependent function types.

2023-09-10 13:04 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
Also, I think we already have `is-family-of-equivalences`

2023-09-10 13:24 UTC, VojtechStep commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
> We should probably define equiv-family somewhere

If by that you mean give a name to `(x :  X) -> A x ≃ B x` the you're in luck, because it's not only already defined, it's even defined twice 😃. Once in univalence (`equiv-fam`) and once in equivalences (`fam-equiv`).

2023-09-10 13:25 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
Lol! Thanks for spotting that. It should probably go in a separate file called `families of equivalences`, and then we can have the definition of `is-family-of-equivalences` there too.

2023-09-10 13:27 UTC, fredrik-bakke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
I hope you are not expecting me to do that as part of this PR

2023-09-10 13:34 UTC, EgbertRijke commented on src/foundation/logical-equivalences.lagda.md
> +  iff-Π :
Sure, let me create an issue then.

2023-09-10 13:50 UTC, EgbertRijke commented on src/foundation/slice.lagda.md
> +    f ~ (g ∘ map-hom-slice f g h)
And that last set of parentheses isn't needed anymore either:) Do we want to omit them in general, or do you prefer these homotopies to be stated with parentheses?

2023-09-10 13:59 UTC, fredrik-bakke commented on src/foundation/slice.lagda.md
> +    f ~ (g ∘ map-hom-slice f g h)
I think in cases like this we can omit the parentheses

2023-09-10 21:04 UTC, fredrik-bakke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
Would it make sense to move these corollaries and the main theorem to its own file? I'm struggling to find anywhere natural to place them that doesn't introduce cyclic dependencies. If so, what should the file be called?

2023-09-10 21:05 UTC, fredrik-bakke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
Placing it in subuniverses didn't really make sense to me, unless every corollary is placed elsewhere.

2023-09-10 21:09 UTC, fredrik-bakke commented on src/foundation/functoriality-function-types.lagda.md
> +### A map is truncated iff postcomposition by it is truncated
I'm struggling to find a place to put this that doesn't introduce cyclic dependencies, and this is taking a lot of my time. Is it okay if we leave it here for now?

2023-09-10 21:11 UTC, fredrik-bakke commented on src/foundation/functoriality-function-types.lagda.md
> +### A map is truncated iff postcomposition by it is truncated
Maybe a passable argument for keeping it here for the moment is that truncated maps is a generalization of equivalences, and this theorem for equivalences is something that belongs naturally in this file? 🙃

2023-09-10 21:11 UTC, EgbertRijke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
I guess one can argue that even though these corollaries mention the universe of propositions, the universe of sets, and the universe of truncated types, they are still about the functoriality of Pi-types. Perhaps it is ok to have them here.

2023-09-10 21:20 UTC, EgbertRijke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
The other option would be to have separate files for `precomposition-dependent-functions` and `postcomposition-dependent-functions`, but this would require some thought before we start doing that. For example, is it really sensible?

In `functoriality-dependent-function-types` we currently deal with precomposition, postcomposition, and two-sided composition. If we would make a split, would we also want to split the `functoriality-function-types` files? Can we make this split on conceptual grounds?

2023-09-10 21:25 UTC, fredrik-bakke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
I would hope that wouldn't be necessary, but let me think about it a little. Can we perhaps merge this PR and rather make further changes to this when the need arises again?

2023-09-10 21:25 UTC, fredrik-bakke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
Or a better solution is found

2023-09-10 21:31 UTC, EgbertRijke commented on src/foundation-core/functoriality-function-types.lagda.md
> +
Let's at least agree that it is not necessary for this PR. But every time I've factored out an operation from a larger file into its own I've actually been happy with the result, and I could see that happening here too. So I think it's worth some consideration whether we want files for post and precomposition.

2023-09-10 21:32 UTC, EgbertRijke commented on src/foundation/functoriality-function-types.lagda.md
> +### A map is truncated iff postcomposition by it is truncated
Yeah, let's keep it here.

2023-09-10 21:33 UTC, EgbertRijke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +    (f ∘ map-inv-is-coherently-invertible) ~ id
```suggestion
    f ∘ map-inv-is-coherently-invertible ~ id
```

2023-09-10 21:34 UTC, EgbertRijke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +    (map-inv-is-coherently-invertible ∘ f) ~ id
```suggestion
    map-inv-is-coherently-invertible ∘ f ~ id
```

2023-09-10 21:35 UTC, EgbertRijke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +        ( is-retraction-is-invertible H y))
```suggestion
      ( inv (is-retraction-is-invertible H (f (map-inv-is-invertible H y)))) ∙
      ( ap f (is-section-is-invertible H (map-inv-is-invertible H y))) ∙
      ( is-retraction-is-invertible H y)
```

2023-09-10 21:36 UTC, fredrik-bakke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +    (f ∘ map-inv-is-coherently-invertible) ~ id
Already reaping benefits from #712 😊

2023-09-10 21:42 UTC, fredrik-bakke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +        ( is-retraction-is-invertible H y))
turns out it didn't type check with this change

2023-09-10 21:44 UTC, EgbertRijke approved these changes

2023-09-10 21:45 UTC, EgbertRijke commented
Looks good! I went over it one more time, and I'm happy to hit that green button again:)

2023-09-10 21:46 UTC, EgbertRijke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +        ( is-retraction-is-invertible H y))
Ah, sorry! My bad

2023-09-10 21:46 UTC, EgbertRijke commented on src/foundation-core/coherently-invertible-maps.lagda.md
> +    (f ∘ map-inv-is-coherently-invertible) ~ id
Oh yes!

2023-09-10 21:47 UTC, fredrik-bakke commented
Thanks for all the discussions! I'm sorry not everything could be resolved. Still, I think this PR introduces some good improvements overall

2023-09-10 21:48 UTC, EgbertRijke commented
They're definitely improvements! Maybe things are not yet ready to be printed on t-shirts, but hey, you made it better than it was before!

2023-09-10 21:52 UTC, EgbertRijke commented
Brr some error again

2023-09-10 21:52 UTC, fredrik-bakke commented
working on it

2023-09-10 22:00 UTC, fredrik-bakke commented
Some definitions had randomly disappeared in the merging process. Git isn't always perfect when it comes to this.

2023-09-10 22:04 UTC, EgbertRijke commented
That's the first time I hear of such a bug. Quite a bad one!

2023-09-10 22:06 UTC, fredrik-bakke commented
I guess it is also possible that I wasn't paying enough attention at some point 😅

2023-09-10 22:07 UTC, EgbertRijke commented on src/foundation/homotopies.lagda.md
> +  equiv-left-transpose-htpy-concat' : (H ~ (K ∙h L)) ≃ (((inv-htpy K) ∙h H) ~ L)
Doesn't this line have way too many parentheses?

2023-09-10 22:07 UTC, EgbertRijke commented on src/foundation/homotopies.lagda.md
> +  equiv-left-transpose-htpy-concat' : (H ~ (K ∙h L)) ≃ (((inv-htpy K) ∙h H) ~ L)
I see 3 pairs that can be removed:)

2023-09-10 22:08 UTC, EgbertRijke commented on src/foundation/homotopies.lagda.md
> +    (H ~ (K ∙h L)) ≃ ((H ∙h (inv-htpy L)) ~ K)
Same here

2023-09-10 22:09 UTC, fredrik-bakke commented
Sorry, I had only restored what was there before.

2023-09-10 22:11 UTC, EgbertRijke commented
Great! Let's see if the checks will be done before I find something else that can be changed XD

2023-09-10 22:13 UTC, fredrik-bakke commented
I'm glad you're eager about the new operator system, but let's save it for newer PRs :)

2023-09-10 22:22 UTC, fredrik-bakke commented
😂 @EgbertRijke

2023-09-10 22:22 UTC, merged

2023-09-10 22:52 UTC, EgbertRijke commented
What's up?:)